# Generated by Django 5.2.5 on 2025-08-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('jewelry', 'Jewelry'), ('documents', 'Documents'), ('keys', 'Keys'), ('bags', 'Bags'), ('books', 'Books'), ('sports', 'Sports Equipment'), ('toys', 'Toys'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found'), ('claimed', 'Claimed')], default='lost', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the item', null=True, upload_to='item_images/')),
                ('location_lost_found', models.CharField(blank=True, help_text='Where was this item lost or found?', max_length=200)),
                ('date_lost_found', models.DateTimeField(blank=True, help_text='When was this item lost or found?', null=True)),
                ('contact_info', models.TextField(blank=True, help_text='Additional contact information or instructions')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
