# Generated by Django 5.2.5 on 2025-09-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_conversation_message_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='body',
            field=models.TextField(default='Empty message'),
        ),
    ]
