# Generated by Django 5.2.5 on 2025-09-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_message_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
    ]
